seed: 42
setup:
  N_hidden: 10
  N_fake: 10
  train_size: False
  valid_size: 0.2
features:
  subset: False
  connectivity:
    cutoff: 100
  transformation:
    skew_threshold: 0
    inclusions: ["degree", "neighbors", "size"]
    exclusions: ["cos", "JC",  "PA", "RA", "AA"]
    drop_vars: True
  selection:
    skip: False
    model:
      C: 0.01
      penalty: "l1"
      dual: False
models:
  Jacob:
    target: "RA_undirected"
    threshold: "median"
  LR:
    solver: "liblinear"
  SVM:
    kernel: "rbf"
    gamma: "scale"
    C: 10
    probability: True
  RF:
    n_estimators: 500
    random_state: 42
  ET:
    n_estimators: 500
    random_state: 42
  GB:
    random_state: 42
  IF:
    n_estimators: 500
    behaviour: "new"
    contamination: 0.5
    random_state: 42
  HGB:
    random_state: 42
  AB:
    n_estimators: 500
    random_state: 42
  XG:
    random_state: 42
  NN:
    layers:
      depth: 5
      dropout: False
      dense:
        activation: "tanh"
        use_bias: True
      output:
        activation: "sigmoid"
        use_bias: True
    SGD:
      lr: 0.01
      decay: 1e-6
      momentum: 0.9
      nesterov: True
    compile:
      loss: "binary_crossentropy"
      metrics: ["accuracy"]
    fit:
      epochs: 30
      batch_size: 128
predict:
  probability: True
