seed: 42
setup:
  N_hidden: 10
  N_fake: 10
  train_size: 100000
  valid_size: False
features:
  subset: 200
  connectivity:
    cutoff: 100
models:
  LR:
    solver: "liblinear"
  SVM:
    kernel: "linear"
    gamma: "scale"
    probability: True
  RF:
    n_estimators: 500
    random_state: 42
  AB:
    n_estimators: 500
    random_state: 42
  XG:
    random_state: 42
  NN:
    layers:
      depth: 3
      dense:
        activation: "tanh"
        use_bias: True
      output:
        activation: "sigmoid"
        use_bias: True
    SGD:
      lr: 0.01
      decay: 1e-6
      momentum: 0.9
      nesterov: True
    compile:
      loss: "binary_crossentropy"
      metrics: ["accuracy"]
    fit:
      epochs: 30
      batch_size: 128
predict:
  probability: True
